-- =====================================================
-- TODAS AS RECEITAS ANCESTRAIS - 60 RECEITAS
-- =====================================================

-- 1. Iogurte Caseiro Natural
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Iogurte Caseiro Natural', NULL, NULL, 'breakfast', 'medium', NULL, 480, 4, '[{"item": "Leite integral", "amount": "1 litro"}, {"item": "Iogurte natural sem açúcar", "amount": "2 colheres de sopa"}]'::jsonb, '["Aqueça o leite até atingir 45°C", "Adicione o iogurte ao leite morno e misture", "Deixe em local protegido por 8 a 24 horas", "Refrigere por 2 horas"]'::jsonb, NULL, NULL, ARRAY['probiotico','fermentado','cafe-da-manha'], false, NULL);

-- 2. Kefir de Leite
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Kefir de Leite', NULL, NULL, 'breakfast', 'easy', NULL, 1080, 2, '[{"item": "Leite integral", "amount": "2 xícaras"}, {"item": "Grãos de kefir", "amount": "1 colher de sopa"}]'::jsonb, '["Coloque grãos e leite em pote de vidro", "Deixe por 18 a 24 horas", "Mexa após 12 horas", "Coe e reserve grãos"]'::jsonb, NULL, NULL, ARRAY['probiotico','fermentado','cafe-da-manha'], false, NULL);

-- 3. Queijo Labane Cremoso
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Queijo Labane Cremoso', NULL, NULL, 'breakfast', 'easy', NULL, 720, 6, '[{"item": "Iogurte natural", "amount": "1 litro"}, {"item": "Sal marinho", "amount": "a gosto"}]'::jsonb, '["Despeje iogurte em pano limpo", "Amarre em trouxinha", "Pendure por 12 a 24 horas", "Tempere com sal e azeite"]'::jsonb, NULL, NULL, ARRAY['proteico','cafe-da-manha'], false, NULL);

-- 4. Cenouras Fermentadas com Gengibre
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Cenouras Fermentadas com Gengibre', NULL, NULL, 'snack', 'medium', NULL, 4320, 8, '[{"item": "Cenouras raladas", "amount": "4 xícaras"}, {"item": "Gengibre fresco ralado", "amount": "1 colher de sopa"}, {"item": "Sal marinho", "amount": "1 colher de sopa"}]'::jsonb, '["Misture e amasse até liberar sucos", "Pressione em pote de vidro", "Deixe 3 dias em temperatura ambiente", "Refrigere"]'::jsonb, NULL, NULL, ARRAY['fermentado','vegano','sem-gluten'], false, NULL);

-- 5. Pepinos Fermentados
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Pepinos Fermentados', NULL, NULL, 'snack', 'medium', NULL, 4320, 8, '[{"item": "Pepinos japoneses", "amount": "5 unidades"}, {"item": "Sementes de mostarda", "amount": "1 colher de sopa"}, {"item": "Sal marinho", "amount": "1 colher de sopa"}, {"item": "Água filtrada", "amount": "1 copo"}]'::jsonb, '["Coloque pepinos e temperos no pote", "Cubra com líquidos", "Deixe 3 dias em temperatura ambiente", "Refrigere"]'::jsonb, NULL, NULL, ARRAY['fermentado','vegano','sem-gluten'], false, NULL);

-- 6. Conserva de Beterrabas Assadas
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Conserva de Beterrabas Assadas', NULL, NULL, 'snack', 'medium', NULL, 4360, 8, '[{"item": "Beterrabas médias em fatias", "amount": "12 unidades"}, {"item": "Sal marinho", "amount": "1 colher de sopa"}, {"item": "Água filtrada", "amount": "1 copo"}]'::jsonb, '["Asse beterrabas a 150°C por 40 min", "Coloque no pote com sal e água", "Fermente 3 dias", "Refrigere"]'::jsonb, NULL, NULL, ARRAY['fermentado','vegano','sem-gluten'], false, NULL);

-- 7. Mostarda Caseira Fermentada
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Mostarda Caseira Fermentada', NULL, NULL, 'snack', 'medium', NULL, 4320, 10, '[{"item": "Mostarda em pó", "amount": "1,5 copo"}, {"item": "Água filtrada", "amount": "0,5 copo"}, {"item": "Soro de leite", "amount": "2 colheres de sopa"}, {"item": "Sal marinho", "amount": "2 colheres de chá"}, {"item": "Suco de limão", "amount": "1 unidade"}]'::jsonb, '["Misture todos ingredientes", "Coloque em vidro deixando espaço", "Deixe 3 dias em temperatura ambiente", "Refrigere quando pronto"]'::jsonb, NULL, NULL, ARRAY['fermentado','sem-gluten'], false, NULL);

-- 8. Ketchup Caseiro Fermentado
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Ketchup Caseiro Fermentado', NULL, NULL, 'snack', 'medium', NULL, 4320, 12, '[{"item": "Pasta de tomate orgânica", "amount": "3 xícaras"}, {"item": "Soro de leite", "amount": "1/4 xícara"}, {"item": "Sal marinho", "amount": "1 colher de sopa"}, {"item": "Mel ou melado", "amount": "1/4 xícara"}, {"item": "Alho amassado", "amount": "3 dentes"}]'::jsonb, '["Bata todos ingredientes no liquidificador", "Transfira para vidro", "Deixe 2 a 3 dias em temperatura ambiente", "Refrigere quando ácido"]'::jsonb, NULL, NULL, ARRAY['fermentado','sem-gluten'], false, NULL);

-- 9. Chutney de Abacaxi
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Chutney de Abacaxi', NULL, NULL, 'snack', 'easy', NULL, 2880, 6, '[{"item": "Abacaxi pequeno picado", "amount": "1 unidade"}, {"item": "Coentro", "amount": "1 maço"}, {"item": "Gengibre", "amount": "1 colher de sopa"}, {"item": "Sal", "amount": "1 colher de chá"}, {"item": "Suco de limão", "amount": "2 colheres de sopa"}]'::jsonb, '["Misture frutas e ervas no pote", "Pressione levemente", "Cubra com líquidos", "Fermente 2 dias"]'::jsonb, NULL, NULL, ARRAY['fermentado','vegano','sem-gluten'], false, NULL);

-- 10. Alho Fermentado
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Alho Fermentado', NULL, NULL, 'snack', 'hard', NULL, 10080, 10, '[{"item": "Alho descascado", "amount": "1 xícara"}, {"item": "Água", "amount": "suficiente para cobrir"}, {"item": "Sal marinho", "amount": "2% do peso da água"}]'::jsonb, '["Encha pote com alho", "Cubra com salmoura", "Deixe fermentar de dias a meses", "Agite ocasionalmente"]'::jsonb, NULL, NULL, ARRAY['fermentado','vegano','sem-gluten'], false, NULL);

-- 11. Caldo de Ossos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Caldo de Ossos', NULL, NULL, 'lunch', 'medium', NULL, 1440, 8, '[{"item": "Ossos com medula", "amount": "1,5 kg"}, {"item": "Pés de galinha", "amount": "4 unidades"}, {"item": "Água", "amount": "3 litros"}, {"item": "Vinagre de maçã", "amount": "2 colheres de sopa"}, {"item": "Vegetais variados", "amount": "a gosto"}]'::jsonb, '["Asse ossos a 200°C por 30 min", "Coloque ossos, água e vinagre na panela", "Descanse 30 min", "Adicione vegetais e cozinhe 12 a 24h em fogo baixo", "Coe e descarte sólidos"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 12. Caldo de Frango
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Caldo de Frango', NULL, NULL, 'lunch', 'medium', NULL, 480, 8, '[{"item": "Frango inteiro ou partes", "amount": "1,5 kg"}, {"item": "Pés de frango", "amount": "2 a 4 unidades"}, {"item": "Água", "amount": "4 litros"}, {"item": "Vinagre de maçã", "amount": "2 colheres de sopa"}, {"item": "Vegetais", "amount": "a gosto"}]'::jsonb, '["Coloque frango, água, vinagre e vegetais na panela", "Descanse 1 hora", "Ferva e limpe espuma", "Cozinhe 6 a 8 horas em fogo mínimo"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 13. Guacamole Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Guacamole Ancestral', NULL, NULL, 'snack', 'easy', 10, NULL, 4, '[{"item": "Abacates maduros", "amount": "2 unidades"}, {"item": "Limão", "amount": "1 unidade"}, {"item": "Tomate picado", "amount": "1 unidade"}, {"item": "Cebola roxa", "amount": "1/4 unidade"}, {"item": "Alho", "amount": "1 dente"}, {"item": "Azeite", "amount": "1 colher de sopa"}, {"item": "Cominho, coentro, sal e pimenta", "amount": "a gosto"}]'::jsonb, '["Amasse abacate com garfo", "Adicione limão imediatamente", "Misture demais ingredientes", "Ajuste tempero"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten'], false, NULL);

-- 14. Molho Pesto Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Molho Pesto Ancestral', NULL, NULL, 'snack', 'easy', 10, NULL, 6, '[{"item": "Manjericão fresco", "amount": "1 maço"}, {"item": "Nozes ou castanhas germinadas", "amount": "1/4 xícara"}, {"item": "Azeite extra virgem", "amount": "1/4 xícara"}, {"item": "Queijo parmesão", "amount": "2 colheres de sopa"}, {"item": "Alho", "amount": "1 dente"}, {"item": "Suco de limão", "amount": "1/2 unidade"}]'::jsonb, '["Coloque todos ingredientes no processador", "Bata até formar pasta", "Ajuste consistência com azeite", "Tempere com sal e pimenta"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 15. Hummus de Grão-de-Bico
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Hummus de Grão-de-Bico', NULL, NULL, 'snack', 'medium', 720, 60, 8, '[{"item": "Grão-de-bico", "amount": "2 xícaras"}, {"item": "Tahine", "amount": "1/4 xícara"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Limão", "amount": "1 unidade"}, {"item": "Azeite", "amount": "2 colheres de sopa"}, {"item": "Cominho", "amount": "1 colher de chá"}]'::jsonb, '["Deixe grão-de-bico de molho por 12h", "Cozinhe com bicarbonato até desmanchar", "Bata no processador com temperos e gelo", "Ajuste cremosidade"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten','proteico'], false, NULL);

-- 16. Ginger Bug
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Ginger Bug', NULL, NULL, 'snack', 'medium', NULL, 7200, 4, '[{"item": "Gengibre ralado com casca", "amount": "2 colheres de sopa"}, {"item": "Açúcar", "amount": "2 colheres de sopa"}, {"item": "Água sem cloro", "amount": "1 xícara"}]'::jsonb, '["Misture tudo em frasco de vidro", "Cubra com pano e elástico", "Alimente diariamente por 5 dias com gengibre e açúcar", "Use quando borbulhar"]'::jsonb, NULL, NULL, ARRAY['fermentado','probiotico','vegano'], false, NULL);

-- 17. Refrigerante de Limonada Fermentada
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Refrigerante de Limonada Fermentada', NULL, NULL, 'snack', 'medium', NULL, 2880, 4, '[{"item": "Água", "amount": "1 litro"}, {"item": "Suco de limão", "amount": "3 unidades"}, {"item": "Raspas de limão", "amount": "1 unidade"}, {"item": "Açúcar mascavo ou mel", "amount": "1/4 xícara"}, {"item": "Líquido de Ginger Bug", "amount": "1/4 xícara"}]'::jsonb, '["Misture base da limonada até dissolver açúcar", "Adicione Ginger Bug coado", "Transfira para garrafa hermética", "Fermente 24h a 48h", "Refrigere quando gaseificar"]'::jsonb, NULL, NULL, ARRAY['fermentado','probiotico','vegano'], false, NULL);

-- 18. Kombucha Primeira Fermentação
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Kombucha Primeira Fermentação', NULL, NULL, 'snack', 'hard', NULL, 14400, 12, '[{"item": "SCOBY", "amount": "1 unidade"}, {"item": "Açúcar orgânico", "amount": "1 xícara"}, {"item": "Sachês de chá", "amount": "4-6 unidades"}, {"item": "Água", "amount": "3 litros"}, {"item": "Kombucha pronta (starter)", "amount": "1/2 xícara"}]'::jsonb, '["Faça chá forte com açúcar", "Esfrie e misture água restante", "Coloque no pote com SCOBY e starter", "Cubra com pano", "Deixe 7 a 14 dias"]'::jsonb, NULL, NULL, ARRAY['fermentado','probiotico','vegano'], false, NULL);

-- 19. Leite de Coco Caseiro
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Leite de Coco Caseiro', NULL, NULL, 'breakfast', 'easy', 5, NULL, 3, '[{"item": "Coco seco picado", "amount": "1 unidade"}, {"item": "Água morna", "amount": "3 xícaras"}]'::jsonb, '["Bata no liquidificador por 3 minutos", "Coe em pano fino"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten','cafe-da-manha'], false, NULL);

-- 20. Chai Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Chai Ancestral', NULL, NULL, 'breakfast', 'easy', 20, NULL, 4, '[{"item": "Água", "amount": "2 xícaras"}, {"item": "Canela em pau", "amount": "1 unidade"}, {"item": "Cardamomo", "amount": "4 sementes"}, {"item": "Cravo", "amount": "3 unidades"}, {"item": "Gengibre fresco", "amount": "1 pedaço"}, {"item": "Cúrcuma", "amount": "1 colher de chá"}, {"item": "Pimenta-do-reino", "amount": "1 pitada"}, {"item": "Chá preto", "amount": "2 sachês"}, {"item": "Leite", "amount": "1 xícara"}]'::jsonb, '["Ferva especiarias na água por 15 min", "Adicione chá preto no fim", "Adicione leite e aqueça sem ferver", "Coe e sirva"]'::jsonb, NULL, NULL, ARRAY['sem-gluten','cafe-da-manha'], false, NULL);

-- 21. Golden Milk
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Golden Milk', NULL, NULL, 'breakfast', 'easy', 10, NULL, 2, '[{"item": "Leite de coco", "amount": "2 xícaras"}, {"item": "Cúrcuma", "amount": "1 colher de chá"}, {"item": "Gengibre", "amount": "1/2 colher de chá"}, {"item": "Canela", "amount": "1/4 colher de chá"}, {"item": "Pimenta-do-reino", "amount": "1 pitada"}, {"item": "Óleo de coco ou ghee", "amount": "1 colher de chá"}, {"item": "Mel", "amount": "a gosto"}]'::jsonb, '["Aqueça leite com especiarias e gordura", "Cozinhe 5-7 min em fogo baixo", "Coe e adoce com mel"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten','cafe-da-manha'], false, NULL);

-- 22. Shakshuka Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Shakshuka Ancestral', NULL, NULL, 'breakfast', 'medium', 10, 20, 4, '[{"item": "Ovos caipiras", "amount": "4 a 6 unidades"}, {"item": "Tomates maduros", "amount": "4 unidades"}, {"item": "Cebola fatiada", "amount": "1 unidade"}, {"item": "Alho", "amount": "3 dentes"}, {"item": "Azeite ou ghee", "amount": "2 colheres de sopa"}, {"item": "Páprica doce", "amount": "1 colher de chá"}, {"item": "Cominho", "amount": "1 colher de chá"}, {"item": "Sal", "amount": "a gosto"}, {"item": "Coentro ou salsa", "amount": "a gosto"}]'::jsonb, '["Refogue cebola e alho até dourarem", "Adicione tomates e especiarias, cozinhe 10-15 min", "Abra buracos no molho e quebre ovos", "Tampe e cozinhe 5 min", "Finalize com ervas"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten','cafe-da-manha'], false, NULL);

-- 23. Pão de Queijo de Polvilho
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Pão de Queijo de Polvilho', NULL, NULL, 'breakfast', 'easy', 15, 25, 12, '[{"item": "Polvilho azedo", "amount": "2 xícaras"}, {"item": "Manteiga", "amount": "1/2 xícara"}, {"item": "Gemas caipiras", "amount": "2 unidades"}, {"item": "Queijo ralado", "amount": "1 xícara"}, {"item": "Leite", "amount": "1/2 xícara"}]'::jsonb, '["Misture todos ingredientes", "Faça bolinhas", "Asse a 180°C por 25 minutos"]'::jsonb, NULL, NULL, ARRAY['sem-gluten','cafe-da-manha'], false, NULL);

-- 24. Smoothie Energético
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Smoothie Energético', NULL, NULL, 'breakfast', 'easy', 5, NULL, 2, '[{"item": "Banana", "amount": "2 unidades"}, {"item": "Abacate", "amount": "1/2 unidade"}, {"item": "Ovo caipira cru", "amount": "1 unidade"}, {"item": "Leite vegetal ou de coco", "amount": "1 xícara"}, {"item": "Mel", "amount": "1 colher de sopa"}]'::jsonb, '["Bata todos ingredientes no liquidificador", "Sirva imediatamente"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten','cafe-da-manha'], false, NULL);

-- 25. Arroz Ancestral com Caldo de Ossos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Arroz Ancestral com Caldo de Ossos', NULL, NULL, 'lunch', 'easy', 720, 30, 4, '[{"item": "Arroz integral ou branco", "amount": "1 xícara"}, {"item": "Caldo de ossos", "amount": "2 xícaras"}, {"item": "Manteiga ou banha", "amount": "1 colher de sopa"}, {"item": "Alho e cebola", "amount": "a gosto"}]'::jsonb, '["Deixe arroz de molho com vinagre por 8-12h", "Enxágue bem", "Refogue alho e cebola na gordura", "Adicione arroz e refogue", "Junte caldo quente e cozinhe até secar"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 26. Feijão Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Feijão Ancestral', NULL, NULL, 'lunch', 'medium', 720, 120, 6, '[{"item": "Feijão", "amount": "2 xícaras"}, {"item": "Caldo de ossos", "amount": "1 xícara"}, {"item": "Banha de porco ou manteiga", "amount": "2 colheres de sopa"}, {"item": "Cebola, alho, louro", "amount": "a gosto"}, {"item": "Sal marinho", "amount": "a gosto"}]'::jsonb, '["Deixe feijão de molho com vinagre 12-24h", "Troque água pelo menos uma vez", "Descarte água e cozinhe até macio", "Refogue cebola e alho na banha", "Adicione feijão, caldo e louro", "Deixe apurar"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 27. Risoto de Cogumelos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Risoto de Cogumelos', NULL, NULL, 'lunch', 'medium', 720, 30, 4, '[{"item": "Arroz integral demolhado", "amount": "1 xícara"}, {"item": "Cogumelos frescos", "amount": "300g"}, {"item": "Caldo de ossos", "amount": "3 xícaras"}, {"item": "Cebola", "amount": "1 unidade"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Ghee", "amount": "2 colheres de sopa"}]'::jsonb, '["Refogue cebola, alho e cogumelos no ghee", "Adicione arroz", "Vá despejando caldo aos poucos", "Mexa sempre até cremoso (20-25 min)"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 28. Costela Bovina Assada
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Costela Bovina Assada', NULL, NULL, 'lunch', 'medium', 15, 240, 6, '[{"item": "Costela bovina", "amount": "1,5 kg"}, {"item": "Alho", "amount": "4 dentes"}, {"item": "Alecrim e tomilho", "amount": "a gosto"}, {"item": "Sal marinho e pimenta", "amount": "a gosto"}, {"item": "Caldo de ossos", "amount": "1/2 xícara"}]'::jsonb, '["Tempere carne e descanse 2 horas", "Coloque na assadeira com caldo", "Cubra e asse a 160°C por 3-4 horas", "Retire cobertura nos últimos 30 min para dourar"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 29. Carne de Panela com Ossos e Legumes
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Carne de Panela com Ossos e Legumes', NULL, NULL, 'lunch', 'medium', 15, 120, 6, '[{"item": "Carne com osso (acém, músculo ou costela)", "amount": "1 kg"}, {"item": "Banha ou manteiga", "amount": "2 colheres de sopa"}, {"item": "Cebola", "amount": "1 unidade"}, {"item": "Alho", "amount": "3 dentes"}, {"item": "Cenouras", "amount": "2 unidades"}, {"item": "Batatas ou mandiocas", "amount": "2 unidades"}, {"item": "Louro", "amount": "1 folha"}, {"item": "Caldo de ossos", "amount": "2 xícaras"}]'::jsonb, '["Sele carne na gordura até dourar", "Refogue cebola e alho", "Volte carne, adicione legumes, louro e caldo", "Tampe e cozinhe 2 horas em fogo baixo"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 30. Ensopado de Rabo de Boi
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Ensopado de Rabo de Boi', NULL, NULL, 'lunch', 'hard', 20, 60, 6, '[{"item": "Rabo de boi em pedaços", "amount": "1 kg"}, {"item": "Azeite ou banha", "amount": "2 colheres de sopa"}, {"item": "Cebola", "amount": "1 unidade"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Batatas", "amount": "3 unidades"}, {"item": "Cenouras", "amount": "2 unidades"}, {"item": "Vinho tinto seco", "amount": "1 xícara"}, {"item": "Caldo de ossos", "amount": "2 xícaras"}, {"item": "Louro", "amount": "1 folha"}]'::jsonb, '["Tempere e sele rabo na panela de pressão", "Adicione cebola e alho", "Use vinho para soltar fundo da panela", "Adicione caldo, louro e legumes", "Cozinhe na pressão por 45 min a 1 hora"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 31. Almôndegas de Carne com Fígado
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Almôndegas de Carne com Fígado', NULL, NULL, 'lunch', 'medium', 20, 20, 6, '[{"item": "Carne moída", "amount": "300g"}, {"item": "Fígado bovino em pasta", "amount": "200g"}, {"item": "Ovo caipira", "amount": "1 unidade"}, {"item": "Cebola ralada", "amount": "1 unidade"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Salsa", "amount": "a gosto"}, {"item": "Páprica", "amount": "1 colher de chá"}, {"item": "Sal e pimenta", "amount": "a gosto"}]'::jsonb, '["Pulse fígado no processador até virar pasta", "Misture com carne e demais ingredientes", "Modele bolinhas", "Frite na manteiga ou banha até dourarem"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 32. Hambúrguer Ancestral com Cebolas
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Hambúrguer Ancestral com Cebolas', NULL, NULL, 'lunch', 'easy', 10, 15, 4, '[{"item": "Carne moída", "amount": "500g"}, {"item": "Cebola em rodelas", "amount": "2 unidades"}, {"item": "Ghee ou manteiga", "amount": "2 colheres de sopa"}, {"item": "Sal e pimenta", "amount": "a gosto"}]'::jsonb, '["Molde hambúrgueres", "Grelhe no ghee por 4 min cada lado", "Reserve", "Caramelize cebolas no mesmo ghee", "Sirva hambúrguer com cebolas"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 33. Bife de Fígado Acebolado
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Bife de Fígado Acebolado', NULL, NULL, 'lunch', 'easy', 10, 10, 4, '[{"item": "Fígado em fatias finas", "amount": "500g"}, {"item": "Suco de limão", "amount": "1 unidade"}, {"item": "Cebola em rodelas", "amount": "2 unidades"}, {"item": "Manteiga ou banha", "amount": "2 colheres de sopa"}, {"item": "Sal e pimenta", "amount": "a gosto"}]'::jsonb, '["Tempere fígado com limão, sal e pimenta", "Refogue cebolas na manteiga e reserve", "Sele fígado rapidamente (1-2 min cada lado)", "Misture cebolas e sirva"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 34. Coxas de Frango com Mostarda e Mel
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Coxas de Frango com Mostarda e Mel', NULL, NULL, 'lunch', 'easy', 10, 45, 4, '[{"item": "Coxas de frango", "amount": "8 unidades"}, {"item": "Mostarda dijon", "amount": "2 colheres de sopa"}, {"item": "Mel", "amount": "2 colheres de sopa"}, {"item": "Páprica", "amount": "1 colher de chá"}, {"item": "Azeite", "amount": "2 colheres de sopa"}]'::jsonb, '["Misture mostarda, mel, páprica e azeite", "Passe nas coxas", "Asse a 200°C por 45 minutos"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 35. Frango com Cogumelos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Frango com Cogumelos', NULL, NULL, 'lunch', 'medium', 10, 25, 4, '[{"item": "Peito de frango em cubos", "amount": "500g"}, {"item": "Cogumelos frescos", "amount": "300g"}, {"item": "Manteiga", "amount": "2 colheres de sopa"}, {"item": "Creme de leite fresco ou leite de coco", "amount": "1/2 xícara"}, {"item": "Caldo de frango", "amount": "1 xícara"}, {"item": "Alho e cebola", "amount": "a gosto"}]'::jsonb, '["Sele frango na manteiga e reserve", "Adicione cogumelos, creme e caldo", "Cozinhe por 15 minutos até engrossar"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 36. Curry de Frango
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Curry de Frango', NULL, NULL, 'lunch', 'medium', 15, 30, 4, '[{"item": "Peito de frango em cubos", "amount": "500g"}, {"item": "Curry em pó", "amount": "2 colheres de sopa"}, {"item": "Leite de coco", "amount": "1 lata"}, {"item": "Tomate picado", "amount": "2 unidades"}, {"item": "Cenoura", "amount": "1 unidade"}, {"item": "Gengibre fresco ralado", "amount": "1 colher de sopa"}, {"item": "Alho e cebola", "amount": "a gosto"}, {"item": "Coentro", "amount": "a gosto"}]'::jsonb, '["Refogue alho, cebola e gengibre", "Doure frango", "Adicione curry, tomate, cenoura e leite de coco", "Cozinhe por 30 min", "Finalize com coentro"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 37. Sopa de Frango com Legumes
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Sopa de Frango com Legumes', NULL, NULL, 'lunch', 'easy', 15, 30, 6, '[{"item": "Frango desfiado", "amount": "2 xícaras"}, {"item": "Caldo de ossos", "amount": "1 litro"}, {"item": "Cenoura", "amount": "2 unidades"}, {"item": "Batata-doce", "amount": "2 unidades"}, {"item": "Abobrinha", "amount": "1 unidade"}, {"item": "Salsão", "amount": "2 talos"}, {"item": "Alho, cebola e ervas", "amount": "a gosto"}]'::jsonb, '["Refogue temperos", "Cozinhe legumes duros no caldo por 10 min", "Adicione abobrinha e frango", "Cozinhe mais 10 min"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 38. Moela de Frango ao Molho de Tomate
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Moela de Frango ao Molho de Tomate', NULL, NULL, 'lunch', 'medium', 10, 60, 4, '[{"item": "Moelas de frango", "amount": "500g"}, {"item": "Banha", "amount": "1 colher de sopa"}, {"item": "Tomates maduros", "amount": "4 unidades"}, {"item": "Páprica", "amount": "1 colher de chá"}, {"item": "Caldo de galinha", "amount": "1 xícara"}, {"item": "Cebola e alho", "amount": "a gosto"}]'::jsonb, '["Refogue moelas com cebola e alho", "Adicione tomates e caldo", "Cozinhe em fogo baixo por 1 hora até macias"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 39. Coração de Galinha Salteado
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Coração de Galinha Salteado', NULL, NULL, 'lunch', 'easy', 10, 10, 4, '[{"item": "Corações de galinha", "amount": "500g"}, {"item": "Banha ou manteiga", "amount": "2 colheres de sopa"}, {"item": "Alho", "amount": "3 dentes"}, {"item": "Páprica defumada", "amount": "1 colher de chá"}, {"item": "Sal e pimenta", "amount": "a gosto"}, {"item": "Ervas frescas", "amount": "a gosto"}]'::jsonb, '["Salteie corações em etapas por 7 min", "Adicione alho no final", "Tempere e finalize com ervas"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 40. Patê de Fígado de Galinha
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Patê de Fígado de Galinha', NULL, NULL, 'snack', 'easy', 10, 10, 8, '[{"item": "Fígado de galinha", "amount": "300g"}, {"item": "Cebola", "amount": "1 unidade"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Manteiga", "amount": "2 colheres de sopa"}, {"item": "Vinagre de maçã ou limão", "amount": "1 colher de sopa"}]'::jsonb, '["Refogue cebola e alho", "Adicione fígados e cozinhe 7 min", "Bata tudo no processador com vinagre até cremoso", "Dura 3 dias na geladeira"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 41. Peixe Inteiro Assado com Limão e Ervas
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Peixe Inteiro Assado com Limão e Ervas', NULL, NULL, 'dinner', 'medium', 15, 30, 4, '[{"item": "Peixe inteiro (robalo, tainha ou dourado)", "amount": "1 unidade"}, {"item": "Limão", "amount": "2 unidades"}, {"item": "Tomilho e salsa", "amount": "a gosto"}, {"item": "Alho e cebola", "amount": "a gosto"}, {"item": "Azeite", "amount": "a gosto"}]'::jsonb, '["Tempere peixe por dentro e por fora", "Recheie cavidade com ervas, cebola e limão", "Pincele azeite", "Asse a 180°C por 25-30 minutos"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 42. Moqueca de Peixe
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Moqueca de Peixe', NULL, NULL, 'lunch', 'medium', 15, 20, 4, '[{"item": "Filés de peixe", "amount": "500g"}, {"item": "Azeite de dendê", "amount": "2 colheres de sopa"}, {"item": "Pimentão", "amount": "1 unidade"}, {"item": "Tomates", "amount": "2 unidades"}, {"item": "Leite de coco", "amount": "1 lata"}, {"item": "Coentro", "amount": "1 maço"}, {"item": "Alho, cebola e limão", "amount": "a gosto"}]'::jsonb, '["Refogue alho, cebola e pimentão no dendê", "Adicione tomates e leite de coco", "Deixe engrossar", "Coloque peixe e cozinhe 5-10 min", "Finalize com coentro"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 43. Sardinhas ao Molho de Tomate
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Sardinhas ao Molho de Tomate', NULL, NULL, 'lunch', 'easy', 10, 15, 4, '[{"item": "Sardinhas frescas", "amount": "8 unidades"}, {"item": "Tomates", "amount": "4 unidades"}, {"item": "Cebola", "amount": "1 unidade"}, {"item": "Alho", "amount": "3 dentes"}, {"item": "Louro", "amount": "1 folha"}, {"item": "Azeite", "amount": "2 colheres de sopa"}]'::jsonb, '["Faça molho rústico com tomates, cebola, alho e louro", "Coloque sardinhas sobre o molho", "Cozinhe 10-15 min em fogo baixo"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 44. Bobó de Camarão Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Bobó de Camarão Ancestral', NULL, NULL, 'lunch', 'medium', 30, 20, 4, '[{"item": "Camarões", "amount": "500g"}, {"item": "Mandioca cozida", "amount": "500g"}, {"item": "Leite de coco", "amount": "1 lata"}, {"item": "Azeite de dendê", "amount": "2 colheres de sopa"}, {"item": "Tomate, cebola, alho e pimentão", "amount": "a gosto"}, {"item": "Limão", "amount": "1 unidade"}]'::jsonb, '["Bata mandioca com leite de coco", "Refogue temperos no dendê", "Misture purê de mandioca", "Adicione camarões marinados no limão", "Cozinhe 5-7 minutos"]'::jsonb, NULL, NULL, ARRAY['proteico','sem-gluten'], false, NULL);

-- 45. Abóbora Cabotiá Assada
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Abóbora Cabotiá Assada', NULL, NULL, 'lunch', 'easy', 10, 30, 4, '[{"item": "Abóbora cabotiá pequena em fatias", "amount": "1 unidade"}, {"item": "Manteiga derretida", "amount": "3 colheres de sopa"}, {"item": "Canela", "amount": "1 colher de chá"}, {"item": "Sal", "amount": "a gosto"}]'::jsonb, '["Pincele abóbora com manteiga", "Tempere com canela e sal", "Asse a 200°C por 25-30 min até caramelizar"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten'], false, NULL);

-- 46. Cenoura Glaceada com Mel
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Cenoura Glaceada com Mel', NULL, NULL, 'lunch', 'easy', 5, 10, 4, '[{"item": "Cenouras em rodelas", "amount": "4 unidades"}, {"item": "Manteiga", "amount": "2 colheres de sopa"}, {"item": "Mel", "amount": "1 colher de sopa"}, {"item": "Sal e pimenta", "amount": "a gosto"}]'::jsonb, '["Cozinhe cenouras até al dente", "Escorra e leve à frigideira com manteiga e mel", "Cozinhe 2-3 min até brilharem"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 47. Macarrão de Abobrinha
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Macarrão de Abobrinha', NULL, NULL, 'lunch', 'easy', 25, NULL, 4, '[{"item": "Abobrinhas", "amount": "4 unidades"}, {"item": "Tomates", "amount": "2 unidades"}, {"item": "Pimentões", "amount": "2 unidades"}, {"item": "Alho", "amount": "4 dentes"}, {"item": "Azeite", "amount": "3 colheres de sopa"}, {"item": "Ervas frescas (manjericão, orégano, tomilho)", "amount": "a gosto"}, {"item": "Nozes ou pinhões", "amount": "a gosto"}]'::jsonb, '["Use cortador espiral para fazer espaguete de abobrinha", "Misture com sal e deixe 20 min para liberar água", "Adicione vegetais picados, temperos e azeite", "Finalize com nozes"]'::jsonb, NULL, NULL, ARRAY['vegano','sem-gluten','low-carb'], false, NULL);

-- 48. Batatas Fritas Ancestrais
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Batatas Fritas Ancestrais', NULL, NULL, 'snack', 'medium', 65, 10, 4, '[{"item": "Batatas", "amount": "4 unidades"}, {"item": "Banha de porco ou sebo bovino", "amount": "para fritura"}, {"item": "Sal", "amount": "a gosto"}]'::jsonb, '["Corte batatas e deixe de molho em água fria por 1 hora", "Seque muito bem", "Frite a 175°C por 3 min", "Retire e deixe escorrer 5 min", "Frite novamente por 2 min até crocantes"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 49. Cogumelos Salteados com Caldo de Ossos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Cogumelos Salteados com Caldo de Ossos', NULL, NULL, 'lunch', 'easy', 5, 10, 4, '[{"item": "Cogumelos frescos", "amount": "300g"}, {"item": "Manteiga", "amount": "2 colheres de sopa"}, {"item": "Caldo de ossos", "amount": "1 colher de sopa"}, {"item": "Alho", "amount": "2 dentes"}, {"item": "Tomilho e salsinha", "amount": "a gosto"}]'::jsonb, '["Refogue alho na manteiga", "Adicione cogumelos e caldo de ossos", "Salteie por 5-7 minutos", "Finalize com ervas"]'::jsonb, NULL, NULL, ARRAY['sem-gluten'], false, NULL);

-- 50. Bolo de Banana com Aveia Fermentada
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Bolo de Banana com Aveia Fermentada', NULL, NULL, 'dessert', 'medium', 720, 40, 8, '[{"item": "Bananas maduras", "amount": "12 unidades"}, {"item": "Ovos", "amount": "4 unidades"}, {"item": "Aveia hidratada na noite anterior", "amount": "2 xícaras"}, {"item": "Manteiga ou óleo de coco", "amount": "2 colheres de sopa"}]'::jsonb, '["Misture bananas amassadas com ovos", "Adicione aveia escorrida e gordura", "Asse a 180°C por 40 minutos"]'::jsonb, NULL, NULL, ARRAY['sobremesa','sem-gluten'], false, NULL);

-- 51. Pudim de Coco Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Pudim de Coco Ancestral', NULL, NULL, 'dessert', 'medium', 20, 60, 6, '[{"item": "Ovos", "amount": "4 unidades"}, {"item": "Leite de coco", "amount": "2 xícaras"}, {"item": "Mel ou açúcar mascavo", "amount": "1/3 xícara"}, {"item": "Baunilha", "amount": "1 colher de chá"}]'::jsonb, '["Caramelize forma com melado", "Bata ingredientes no liquidificador", "Despeje na forma", "Asse em banho-maria a 180°C por 50-60 min", "Refrigere por 4 horas"]'::jsonb, NULL, NULL, ARRAY['sobremesa','sem-gluten'], false, NULL);

-- 52. Trufas de Cacau e Tâmara
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Trufas de Cacau e Tâmara', NULL, NULL, 'dessert', 'easy', 15, NULL, 12, '[{"item": "Tâmaras hidratadas", "amount": "1 xícara"}, {"item": "Castanhas demolhadas", "amount": "1 xícara"}, {"item": "Cacau em pó", "amount": "1/4 xícara"}, {"item": "Óleo de coco", "amount": "2 colheres de sopa"}]'::jsonb, '["Processe tâmaras com castanhas, cacau e óleo", "Modele bolinhas", "Passe no cacau em pó"]'::jsonb, NULL, NULL, ARRAY['sobremesa','vegano','sem-gluten'], false, NULL);

-- 53. Sorvete de Banana e Frutas Vermelhas
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Sorvete de Banana e Frutas Vermelhas', NULL, NULL, 'dessert', 'easy', 5, NULL, 4, '[{"item": "Bananas congeladas", "amount": "4 unidades"}, {"item": "Frutas vermelhas", "amount": "1 xícara"}, {"item": "Leite de coco", "amount": "1/4 xícara"}]'::jsonb, '["Bata bananas congeladas, frutas e leite no processador", "Processe até consistência de sorvete", "Sirva imediatamente"]'::jsonb, NULL, NULL, ARRAY['sobremesa','vegano','sem-gluten'], false, NULL);

-- 54. Quindim Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Quindim Ancestral', NULL, NULL, 'dessert', 'medium', 15, 40, 12, '[{"item": "Gemas peneiradas", "amount": "4 unidades"}, {"item": "Leite de coco", "amount": "1 xícara"}, {"item": "Melado ou açúcar de coco", "amount": "1/2 xícara"}, {"item": "Coco ralado fresco", "amount": "1 xícara"}]'::jsonb, '["Misture gemas, leite de coco, melado e coco", "Asse em banho-maria por 40 minutos", "Deixe esfriar e desenforme"]'::jsonb, NULL, NULL, ARRAY['sobremesa','sem-gluten'], false, NULL);

-- 55. Doce de Leite Ancestral
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Doce de Leite Ancestral', NULL, NULL, 'dessert', 'medium', 10, 120, 8, '[{"item": "Leite integral", "amount": "1 litro"}, {"item": "Melado de cana", "amount": "1/2 xícara"}]'::jsonb, '["Cozinhe leite com melado em fogo baixo", "Mexa constantemente por 1 a 2 horas", "Cozinhe até reduzir e ficar cremoso"]'::jsonb, NULL, NULL, ARRAY['sobremesa'], false, NULL);

-- 56. Curau de Milho
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Curau de Milho', NULL, NULL, 'dessert', 'easy', 10, 20, 6, '[{"item": "Milho de 6 espigas", "amount": "6 espigas"}, {"item": "Leite de coco", "amount": "500ml"}, {"item": "Melado", "amount": "1/4 xícara"}, {"item": "Canela", "amount": "a gosto"}]'::jsonb, '["Bata milho com leite de coco", "Coe", "Adicione melado e cozinhe até engrossar", "Finalize com canela"]'::jsonb, NULL, NULL, ARRAY['sobremesa','sem-gluten'], false, NULL);

-- 57. Cocada Cremosa com Ovos
INSERT INTO public.recipes (title, description, image_url, category, difficulty, prep_time_minutes, cook_time_minutes, servings, ingredients, instructions, calories_per_serving, nutritional_info, tags, is_published, created_by)
VALUES ('Cocada Cremosa com Ovos', NULL, NULL, 'dessert', 'medium', 10, 30, 8, '[{"item": "Leite de coco", "amount": "2 xícaras"}, {"item": "Gemas", "amount": "4 unidades"}, {"item": "Melado", "amount": "1/2 xícara"}, {"item": "Coco ralado fresco", "amount": "2 xícaras"}]'::jsonb, '["Leve leite de coco, gemas, melado e coco ao fogo", "Mexa até engrossar", "Sirva em potinhos"]'::jsonb, NULL, NULL, ARRAY['sobremesa','sem-gluten'], false, NULL);
