-- =====================================================
-- TABELAS: Sistema de Feed da Comunidade
-- Posts, Likes e Comentários
-- =====================================================

-- =====================================================
-- TABELA: community_posts
-- =====================================================

create table public.community_posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Relacionamento com usuário
  user_id uuid not null,

  -- Conteúdo do post
  content text not null,

  -- Moderação
  is_published boolean not null default true,

  -- Contadores denormalizados (atualizados via triggers)
  likes_count integer not null default 0,
  comments_count integer not null default 0,

  constraint community_posts_pkey primary key (id),
  constraint community_posts_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade
) tablespace pg_default;

-- =====================================================
-- TABELA: community_post_likes
-- =====================================================

create table public.community_post_likes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),

  -- Relacionamentos
  post_id bigint not null,
  user_id uuid not null,

  constraint community_post_likes_pkey primary key (id),
  constraint community_post_likes_post_id_fkey foreign key (post_id)
    references public.community_posts (id) on delete cascade,
  constraint community_post_likes_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade,

  -- Garantir apenas uma curtida por usuário por post
  constraint community_post_likes_unique unique (post_id, user_id)
) tablespace pg_default;

-- =====================================================
-- TABELA: community_post_comments
-- =====================================================

create table public.community_post_comments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Relacionamentos
  post_id bigint not null,
  user_id uuid not null,

  -- Conteúdo do comentário
  content text not null,

  constraint community_post_comments_pkey primary key (id),
  constraint community_post_comments_post_id_fkey foreign key (post_id)
    references public.community_posts (id) on delete cascade,
  constraint community_post_comments_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade
) tablespace pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Índices para community_posts
create index idx_community_posts_user_id on public.community_posts using btree (user_id);
create index idx_community_posts_created_at on public.community_posts using btree (created_at desc);
create index idx_community_posts_published on public.community_posts using btree (is_published);

-- Índices para community_post_likes
create index idx_community_post_likes_post_id on public.community_post_likes using btree (post_id);
create index idx_community_post_likes_user_id on public.community_post_likes using btree (user_id);

-- Índices para community_post_comments
create index idx_community_post_comments_post_id on public.community_post_comments using btree (post_id);
create index idx_community_post_comments_user_id on public.community_post_comments using btree (user_id);
create index idx_community_post_comments_created_at on public.community_post_comments using btree (created_at asc);

-- =====================================================
-- TRIGGERS: Atualizar updated_at automaticamente
-- =====================================================

create or replace function public.update_community_posts_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_community_posts_updated_at
  before update on public.community_posts
  for each row
  execute function public.update_community_posts_updated_at();

create or replace function public.update_community_post_comments_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_community_post_comments_updated_at
  before update on public.community_post_comments
  for each row
  execute function public.update_community_post_comments_updated_at();

-- =====================================================
-- TRIGGERS: Atualizar contadores de likes
-- =====================================================

create or replace function public.increment_post_likes_count()
returns trigger as $$
begin
  update public.community_posts
  set likes_count = likes_count + 1
  where id = new.post_id;
  return new;
end;
$$ language plpgsql;

create trigger increment_likes_count_trigger
  after insert on public.community_post_likes
  for each row
  execute function public.increment_post_likes_count();

create or replace function public.decrement_post_likes_count()
returns trigger as $$
begin
  update public.community_posts
  set likes_count = likes_count - 1
  where id = old.post_id;
  return old;
end;
$$ language plpgsql;

create trigger decrement_likes_count_trigger
  after delete on public.community_post_likes
  for each row
  execute function public.decrement_post_likes_count();

-- =====================================================
-- TRIGGERS: Atualizar contadores de comentários
-- =====================================================

create or replace function public.increment_post_comments_count()
returns trigger as $$
begin
  update public.community_posts
  set comments_count = comments_count + 1
  where id = new.post_id;
  return new;
end;
$$ language plpgsql;

create trigger increment_comments_count_trigger
  after insert on public.community_post_comments
  for each row
  execute function public.increment_post_comments_count();

create or replace function public.decrement_post_comments_count()
returns trigger as $$
begin
  update public.community_posts
  set comments_count = comments_count - 1
  where id = old.post_id;
  return old;
end;
$$ language plpgsql;

create trigger decrement_comments_count_trigger
  after delete on public.community_post_comments
  for each row
  execute function public.decrement_post_comments_count();

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Ativar RLS
alter table public.community_posts enable row level security;
alter table public.community_post_likes enable row level security;
alter table public.community_post_comments enable row level security;

-- =====================================================
-- POLICIES: community_posts
-- =====================================================

-- Todos podem ver posts publicados
create policy "Anyone can view published posts"
  on public.community_posts
  for select
  using (is_published = true);

-- Usuários autenticados podem criar posts
create policy "Authenticated users can create posts"
  on public.community_posts
  for insert
  with check (auth.uid() = user_id);

-- Usuários podem atualizar seus próprios posts
create policy "Users can update their own posts"
  on public.community_posts
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Usuários podem deletar seus próprios posts
create policy "Users can delete their own posts"
  on public.community_posts
  for delete
  using (auth.uid() = user_id);

-- Admins podem ver todos os posts (incluindo não publicados)
create policy "Admins can view all posts"
  on public.community_posts
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- =====================================================
-- POLICIES: community_post_likes
-- =====================================================

-- Todos podem ver curtidas
create policy "Anyone can view likes"
  on public.community_post_likes
  for select
  using (true);

-- Usuários autenticados podem curtir posts
create policy "Authenticated users can like posts"
  on public.community_post_likes
  for insert
  with check (auth.uid() = user_id);

-- Usuários podem remover suas próprias curtidas
create policy "Users can remove their own likes"
  on public.community_post_likes
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- POLICIES: community_post_comments
-- =====================================================

-- Todos podem ver comentários
create policy "Anyone can view comments"
  on public.community_post_comments
  for select
  using (true);

-- Usuários autenticados podem comentar
create policy "Authenticated users can comment"
  on public.community_post_comments
  for insert
  with check (auth.uid() = user_id);

-- Usuários podem atualizar seus próprios comentários
create policy "Users can update their own comments"
  on public.community_post_comments
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Usuários podem deletar seus próprios comentários
create policy "Users can delete their own comments"
  on public.community_post_comments
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- COMENTÁRIOS (Documentação)
-- =====================================================

comment on table public.community_posts is 'Publicações no feed da comunidade';
comment on column public.community_posts.content is 'Conteúdo texto da publicação';
comment on column public.community_posts.is_published is 'Flag para moderação (futuramente)';
comment on column public.community_posts.likes_count is 'Contador denormalizado de curtidas (atualizado via trigger)';
comment on column public.community_posts.comments_count is 'Contador denormalizado de comentários (atualizado via trigger)';

comment on table public.community_post_likes is 'Curtidas em posts da comunidade';
comment on table public.community_post_comments is 'Comentários em posts da comunidade';
