-- =====================================================
-- TABELAS: modules e lessons
-- Sistema de módulos e aulas para plataforma
-- =====================================================

-- =====================================================
-- TABELA: modules
-- =====================================================

create table public.modules (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Informações do módulo
  title text not null,
  description text null,
  thumbnail_url text null,
  order_index integer not null default 0,
  is_published boolean not null default false,

  -- Metadados
  created_by uuid null,

  constraint modules_pkey primary key (id),
  constraint modules_created_by_fkey foreign key (created_by)
    references auth.users (id) on delete set null
) tablespace pg_default;

-- =====================================================
-- TABELA: lessons
-- =====================================================

create table public.lessons (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Relacionamento com módulo
  module_id bigint not null,

  -- Informações da aula
  title text not null,
  description text null,
  duration_minutes integer null,
  thumbnail_url text null,
  order_index integer not null default 0,
  is_published boolean not null default false,

  -- Integração Panda Video (será preenchido futuramente)
  panda_video_id text null,
  panda_video_url text null,

  -- Metadados
  created_by uuid null,

  constraint lessons_pkey primary key (id),
  constraint lessons_module_id_fkey foreign key (module_id)
    references public.modules (id) on delete cascade,
  constraint lessons_created_by_fkey foreign key (created_by)
    references auth.users (id) on delete set null
) tablespace pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Índices para modules
create index idx_modules_order on public.modules using btree (order_index);
create index idx_modules_published on public.modules using btree (is_published);
create index idx_modules_created_by on public.modules using btree (created_by);

-- Índices para lessons
create index idx_lessons_module_id on public.lessons using btree (module_id);
create index idx_lessons_order on public.lessons using btree (module_id, order_index);
create index idx_lessons_published on public.lessons using btree (is_published);
create index idx_lessons_created_by on public.lessons using btree (created_by);

-- =====================================================
-- TRIGGERS: Atualizar updated_at automaticamente
-- =====================================================

create or replace function public.update_modules_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_modules_updated_at
  before update on public.modules
  for each row
  execute function public.update_modules_updated_at();

create or replace function public.update_lessons_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_lessons_updated_at
  before update on public.lessons
  for each row
  execute function public.update_lessons_updated_at();

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Ativar RLS
alter table public.modules enable row level security;
alter table public.lessons enable row level security;

-- =====================================================
-- POLICIES: modules
-- =====================================================

-- Todos podem ver módulos publicados
create policy "Anyone can view published modules"
  on public.modules
  for select
  using (is_published = true);

-- Admins podem ver todos os módulos
create policy "Admins can view all modules"
  on public.modules
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem inserir módulos
create policy "Only admins can insert modules"
  on public.modules
  for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem atualizar módulos
create policy "Only admins can update modules"
  on public.modules
  for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem deletar módulos
create policy "Only admins can delete modules"
  on public.modules
  for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- =====================================================
-- POLICIES: lessons
-- =====================================================

-- Todos podem ver aulas de módulos publicados
create policy "Anyone can view published lessons"
  on public.lessons
  for select
  using (
    exists (
      select 1 from public.modules
      where modules.id = lessons.module_id
      and modules.is_published = true
    )
    and is_published = true
  );

-- Admins podem ver todas as aulas
create policy "Admins can view all lessons"
  on public.lessons
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem inserir aulas
create policy "Only admins can insert lessons"
  on public.lessons
  for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem atualizar aulas
create policy "Only admins can update lessons"
  on public.lessons
  for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem deletar aulas
create policy "Only admins can delete lessons"
  on public.lessons
  for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- =====================================================
-- COMENTÁRIOS (Documentação)
-- =====================================================

comment on table public.modules is 'Módulos de aulas da plataforma';
comment on column public.modules.order_index is 'Ordem de exibição do módulo';
comment on column public.modules.is_published is 'Se o módulo está visível para usuários';

comment on table public.lessons is 'Aulas dentro dos módulos';
comment on column public.lessons.module_id is 'Módulo ao qual a aula pertence';
comment on column public.lessons.panda_video_id is 'ID do vídeo no Panda Video (integração futura)';
comment on column public.lessons.panda_video_url is 'URL do embed do Panda Video (integração futura)';
comment on column public.lessons.order_index is 'Ordem de exibição da aula dentro do módulo';
comment on column public.lessons.is_published is 'Se a aula está visível para usuários';
