-- =====================================================
-- TABELA: quiz_responses
-- Armazena respostas do quiz inicial de cada usuário
-- =====================================================

create table public.quiz_responses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null,

  -- Respostas armazenadas em formato JSONB para flexibilidade
  -- Estrutura: { "p1": valor, "p2": valor, ... "p19": valor }
  -- Para múltipla escolha: array de strings
  responses jsonb not null,

  -- Pontuação total calculada
  total_score integer not null default 0,

  -- Se o quiz foi completado ou está em andamento
  is_completed boolean not null default false,

  constraint quiz_responses_pkey primary key (id),
  constraint quiz_responses_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade,

  -- Constraint para garantir apenas UM quiz por usuário
  -- Se quiser permitir múltiplos quizzes ao longo do tempo, remova esta linha
  constraint quiz_responses_user_id_unique unique (user_id)
) tablespace pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Índice para buscar rapidamente por user_id
create index idx_quiz_responses_user_id on public.quiz_responses using btree (user_id);

-- Índice para queries no JSONB (caso precise buscar respostas específicas)
create index idx_quiz_responses_responses on public.quiz_responses using gin (responses);

-- =====================================================
-- TRIGGER: Atualizar updated_at automaticamente
-- =====================================================

create or replace function public.update_quiz_responses_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_quiz_responses_updated_at
  before update on public.quiz_responses
  for each row
  execute function public.update_quiz_responses_updated_at();

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Ativar RLS
alter table public.quiz_responses enable row level security;

-- Policy: Usuários podem ver apenas suas próprias respostas
create policy "Users can view their own quiz responses"
  on public.quiz_responses
  for select
  using (auth.uid() = user_id);

-- Policy: Usuários podem inserir suas próprias respostas
create policy "Users can insert their own quiz responses"
  on public.quiz_responses
  for insert
  with check (auth.uid() = user_id);

-- Policy: Usuários podem atualizar suas próprias respostas
create policy "Users can update their own quiz responses"
  on public.quiz_responses
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Usuários podem deletar suas próprias respostas (opcional)
create policy "Users can delete their own quiz responses"
  on public.quiz_responses
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- COMENTÁRIOS (Documentação)
-- =====================================================

comment on table public.quiz_responses is 'Armazena respostas do quiz inicial de avaliação de saúde/bem-estar';
comment on column public.quiz_responses.responses is 'Respostas em formato JSON: { "p1": valor, "p2": valor, ... }';
comment on column public.quiz_responses.total_score is 'Pontuação total calculada com base nas respostas';
comment on column public.quiz_responses.is_completed is 'Indica se o quiz foi totalmente completado pelo usuário';

-- =====================================================
-- ESTRUTURA ESPERADA DO JSONB (responses)
-- =====================================================

/*
EXEMPLO DE ESTRUTURA:

{
  "p1": "sim",                              // Pergunta sim/não
  "p2": "baixos_cansada",                   // Múltipla escolha única
  "p3": "moderado",                         // Múltipla escolha única
  "p4": "nao",                              // Pergunta sim/não
  "p5": "algumas_vezes_semana",             // Múltipla escolha única
  "p6": "nao",                              // Pergunta sim/não
  "p7": "tipo_3_4",                         // Múltipla escolha única
  "p8": "nao",                              // Pergunta sim/não
  "p9": ["acne", "eczema"],                 // Múltipla escolha múltipla (array)
  "p10": "nao",                             // Pergunta sim/não
  "p11": ["dor_cabeca", "dor_articular"],   // Múltipla escolha múltipla (array)
  "p12": ["ansiedade"],                     // Múltipla escolha múltipla (array)
  "p13": "algumas_vezes_semana",            // Múltipla escolha única
  "p14": "cansaco_mental",                  // Múltipla escolha única
  "p15": ["hipotireoidismo"],               // Múltipla escolha múltipla (array)
  "p16": ["sensibilidade_gluten"],          // Múltipla escolha múltipla (array)
  "p17": "quase_nunca",                     // Múltipla escolha única
  "p18": "tentei_sem_constancia",           // Múltipla escolha única
  "p19": ["cafe_excesso", "acucar"]         // Múltipla escolha múltipla (array)
}

CÁLCULO DA PONTUAÇÃO:
- O total_score deve ser calculado no backend/composable antes de salvar
- Cada valor de resposta tem uma pontuação associada (vide questionário)
- Para arrays (múltipla escolha), somar a pontuação de cada item selecionado
*/
