-- =====================================================
-- TABELAS: Sistema de Receitas
-- =====================================================

-- =====================================================
-- TABELA: recipes
-- =====================================================

create table public.recipes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Informações básicas da receita
  title text not null,
  description text null,
  image_url text null,

  -- Categorização
  category text not null, -- 'breakfast', 'lunch', 'dinner', 'snack', 'dessert'
  difficulty text not null default 'medium', -- 'easy', 'medium', 'hard'
  prep_time_minutes integer null, -- Tempo de preparo
  cook_time_minutes integer null, -- Tempo de cozimento
  servings integer not null default 1, -- Número de porções

  -- Conteúdo da receita
  ingredients jsonb not null, -- Array de objetos {item: string, amount: string}
  instructions jsonb not null, -- Array de strings (passos)

  -- Informações nutricionais (opcional)
  calories_per_serving integer null,
  nutritional_info jsonb null, -- {protein: number, carbs: number, fats: number, fiber: number}

  -- Tags para busca
  tags text[] null, -- Array de tags: ['sem-gluten', 'vegano', 'low-carb', etc]

  -- Publicação
  is_published boolean not null default false,

  -- Contador denormalizado
  favorites_count integer not null default 0,

  -- Metadados
  created_by uuid null,

  constraint recipes_pkey primary key (id),
  constraint recipes_created_by_fkey foreign key (created_by)
    references auth.users (id) on delete set null
) tablespace pg_default;

-- =====================================================
-- TABELA: recipe_favorites (receitas favoritadas)
-- =====================================================

create table public.recipe_favorites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),

  -- Relacionamentos
  recipe_id bigint not null,
  user_id uuid not null,

  constraint recipe_favorites_pkey primary key (id),
  constraint recipe_favorites_recipe_id_fkey foreign key (recipe_id)
    references public.recipes (id) on delete cascade,
  constraint recipe_favorites_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade,

  -- Garantir apenas um favorito por usuário por receita
  constraint recipe_favorites_unique unique (recipe_id, user_id)
) tablespace pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Índices para recipes
create index idx_recipes_category on public.recipes using btree (category);
create index idx_recipes_difficulty on public.recipes using btree (difficulty);
create index idx_recipes_published on public.recipes using btree (is_published);
create index idx_recipes_created_by on public.recipes using btree (created_by);
create index idx_recipes_tags on public.recipes using gin (tags);

-- Índices para recipe_favorites
create index idx_recipe_favorites_recipe_id on public.recipe_favorites using btree (recipe_id);
create index idx_recipe_favorites_user_id on public.recipe_favorites using btree (user_id);

-- =====================================================
-- TRIGGERS: Atualizar updated_at automaticamente
-- =====================================================

create or replace function public.update_recipes_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_recipes_updated_at
  before update on public.recipes
  for each row
  execute function public.update_recipes_updated_at();

-- =====================================================
-- TRIGGERS: Atualizar contador de favoritos
-- =====================================================

create or replace function public.increment_recipe_favorites_count()
returns trigger as $$
begin
  update public.recipes
  set favorites_count = favorites_count + 1
  where id = new.recipe_id;
  return new;
end;
$$ language plpgsql;

create trigger increment_favorites_count_trigger
  after insert on public.recipe_favorites
  for each row
  execute function public.increment_recipe_favorites_count();

create or replace function public.decrement_recipe_favorites_count()
returns trigger as $$
begin
  update public.recipes
  set favorites_count = favorites_count - 1
  where id = old.recipe_id;
  return old;
end;
$$ language plpgsql;

create trigger decrement_favorites_count_trigger
  after delete on public.recipe_favorites
  for each row
  execute function public.decrement_recipe_favorites_count();

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Ativar RLS
alter table public.recipes enable row level security;
alter table public.recipe_favorites enable row level security;

-- =====================================================
-- POLICIES: recipes
-- =====================================================

-- Todos podem ver receitas publicadas
create policy "Anyone can view published recipes"
  on public.recipes
  for select
  using (is_published = true);

-- Admins podem ver todas as receitas
create policy "Admins can view all recipes"
  on public.recipes
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem inserir receitas
create policy "Only admins can insert recipes"
  on public.recipes
  for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem atualizar receitas
create policy "Only admins can update recipes"
  on public.recipes
  for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem deletar receitas
create policy "Only admins can delete recipes"
  on public.recipes
  for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- =====================================================
-- POLICIES: recipe_favorites
-- =====================================================

-- Todos podem ver favoritos
create policy "Anyone can view favorites"
  on public.recipe_favorites
  for select
  using (true);

-- Usuários autenticados podem favoritar receitas
create policy "Authenticated users can favorite recipes"
  on public.recipe_favorites
  for insert
  with check (auth.uid() = user_id);

-- Usuários podem remover seus próprios favoritos
create policy "Users can remove their own favorites"
  on public.recipe_favorites
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- COMENTÁRIOS (Documentação)
-- =====================================================

comment on table public.recipes is 'Receitas saudáveis da plataforma';
comment on column public.recipes.category is 'Categoria da receita: breakfast, lunch, dinner, snack, dessert';
comment on column public.recipes.difficulty is 'Nível de dificuldade: easy, medium, hard';
comment on column public.recipes.ingredients is 'Array JSON com ingredientes: [{item: string, amount: string}]';
comment on column public.recipes.instructions is 'Array JSON com passos do preparo';
comment on column public.recipes.tags is 'Tags para busca e filtros';
comment on column public.recipes.favorites_count is 'Contador denormalizado de favoritos (atualizado via trigger)';

comment on table public.recipe_favorites is 'Receitas favoritadas pelos usuários';
