-- =====================================================
-- TABELAS: Sistema de Listas de Compras
-- =====================================================

-- =====================================================
-- TABELA: shopping_lists
-- =====================================================

create table public.shopping_lists (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),

  -- Informações básicas da lista
  title text not null,
  description text null,
  image_url text null,

  -- Categorização
  category text not null default 'weekly', -- 'weekly', 'monthly', 'special'

  -- Itens da lista (array de objetos {item: string, quantity: string, category: string})
  -- categorias de item: 'fruits', 'vegetables', 'proteins', 'grains', 'dairy', 'others'
  items jsonb not null,

  -- Tags para busca
  tags text[] null, -- Array de tags: ['low-carb', 'vegetariano', 'econômica', etc]

  -- Publicação
  is_published boolean not null default false,

  -- Contador denormalizado
  favorites_count integer not null default 0,

  -- Metadados
  created_by uuid null,

  constraint shopping_lists_pkey primary key (id),
  constraint shopping_lists_created_by_fkey foreign key (created_by)
    references auth.users (id) on delete set null
) tablespace pg_default;

-- =====================================================
-- TABELA: shopping_list_favorites (listas favoritadas)
-- =====================================================

create table public.shopping_list_favorites (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),

  -- Relacionamentos
  shopping_list_id bigint not null,
  user_id uuid not null,

  constraint shopping_list_favorites_pkey primary key (id),
  constraint shopping_list_favorites_list_id_fkey foreign key (shopping_list_id)
    references public.shopping_lists (id) on delete cascade,
  constraint shopping_list_favorites_user_id_fkey foreign key (user_id)
    references auth.users (id) on delete cascade,

  -- Garantir apenas um favorito por usuário por lista
  constraint shopping_list_favorites_unique unique (shopping_list_id, user_id)
) tablespace pg_default;

-- =====================================================
-- ÍNDICES
-- =====================================================

-- Índices para shopping_lists
create index idx_shopping_lists_category on public.shopping_lists using btree (category);
create index idx_shopping_lists_published on public.shopping_lists using btree (is_published);
create index idx_shopping_lists_created_by on public.shopping_lists using btree (created_by);
create index idx_shopping_lists_tags on public.shopping_lists using gin (tags);

-- Índices para shopping_list_favorites
create index idx_shopping_list_favorites_list_id on public.shopping_list_favorites using btree (shopping_list_id);
create index idx_shopping_list_favorites_user_id on public.shopping_list_favorites using btree (user_id);

-- =====================================================
-- TRIGGERS: Atualizar updated_at automaticamente
-- =====================================================

create or replace function public.update_shopping_lists_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_shopping_lists_updated_at
  before update on public.shopping_lists
  for each row
  execute function public.update_shopping_lists_updated_at();

-- =====================================================
-- TRIGGERS: Atualizar contador de favoritos
-- =====================================================

create or replace function public.increment_shopping_list_favorites_count()
returns trigger as $$
begin
  update public.shopping_lists
  set favorites_count = favorites_count + 1
  where id = new.shopping_list_id;
  return new;
end;
$$ language plpgsql;

create trigger increment_favorites_count_trigger
  after insert on public.shopping_list_favorites
  for each row
  execute function public.increment_shopping_list_favorites_count();

create or replace function public.decrement_shopping_list_favorites_count()
returns trigger as $$
begin
  update public.shopping_lists
  set favorites_count = favorites_count - 1
  where id = old.shopping_list_id;
  return old;
end;
$$ language plpgsql;

create trigger decrement_favorites_count_trigger
  after delete on public.shopping_list_favorites
  for each row
  execute function public.decrement_shopping_list_favorites_count();

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Ativar RLS
alter table public.shopping_lists enable row level security;
alter table public.shopping_list_favorites enable row level security;

-- =====================================================
-- POLICIES: shopping_lists
-- =====================================================

-- Todos podem ver listas publicadas
create policy "Anyone can view published shopping lists"
  on public.shopping_lists
  for select
  using (is_published = true);

-- Admins podem ver todas as listas
create policy "Admins can view all shopping lists"
  on public.shopping_lists
  for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem inserir listas
create policy "Only admins can insert shopping lists"
  on public.shopping_lists
  for insert
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem atualizar listas
create policy "Only admins can update shopping lists"
  on public.shopping_lists
  for update
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- Apenas admins podem deletar listas
create policy "Only admins can delete shopping lists"
  on public.shopping_lists
  for delete
  using (
    exists (
      select 1 from public.profiles
      where profiles.user_id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- =====================================================
-- POLICIES: shopping_list_favorites
-- =====================================================

-- Todos podem ver favoritos
create policy "Anyone can view favorites"
  on public.shopping_list_favorites
  for select
  using (true);

-- Usuários autenticados podem favoritar listas
create policy "Authenticated users can favorite shopping lists"
  on public.shopping_list_favorites
  for insert
  with check (auth.uid() = user_id);

-- Usuários podem remover seus próprios favoritos
create policy "Users can remove their own favorites"
  on public.shopping_list_favorites
  for delete
  using (auth.uid() = user_id);

-- =====================================================
-- COMENTÁRIOS (Documentação)
-- =====================================================

comment on table public.shopping_lists is 'Listas de compras da plataforma';
comment on column public.shopping_lists.category is 'Categoria da lista: weekly (semanal), monthly (mensal), special (especial)';
comment on column public.shopping_lists.items is 'Array JSON com itens: [{item: string, quantity: string, category: string}]';
comment on column public.shopping_lists.tags is 'Tags para busca e filtros';
comment on column public.shopping_lists.favorites_count is 'Contador denormalizado de favoritos (atualizado via trigger)';

comment on table public.shopping_list_favorites is 'Listas de compras favoritadas pelos usuários';
